# Generated by Django 4.2 on 2023-04-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=20)),
                ('Reporting_Period', models.CharField(choices=[('This Week', 'This Week'), ('Next Week', 'Next Week'), ('Upcoming', 'Upcoming'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('Type', models.CharField(choices=[('Problem', 'Problem'), ('Action', 'Action'), ('Event', 'Event'), ('Comment', 'Comment')], max_length=500)),
                ('Type_Description', models.CharField(max_length=200)),
                ('Priority', models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], max_length=40)),
                ('Status', models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Paused', 'Paused'), ('Due', 'Due')], max_length=15)),
                ('Logged_By', models.CharField(choices=[('Shaun', 'Shaun')], max_length=50)),
                ('Responsible', models.CharField(choices=[('Shaun', 'Shaun')], max_length=50)),
                ('Start_Date', models.CharField(max_length=50)),
                ('Target_Date', models.DateField(max_length=50)),
                ('FeedBack', models.CharField(max_length=200)),
            ],
        ),
    ]
